image: Visual Studio 2019

install:
  - cmake --version # expect >= 3.16
  - ninja --version # expect >= 1.10

  - SET SDL_VERSION=2.0.12
  - SET IMG_VERSION=2.0.5
  - SET MIX_VERSION=2.0.4
  - SET TTF_VERSION=2.0.15

  # Updates PATH to support command-line usage of compiler
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

  # Installs SDL2 core
  - appveyor DownloadFile https://libsdl.org/release/SDL2-devel-%SDL_VERSION%-VC.zip
  - unzip -o SDL2-devel-%SDL_VERSION%-VC.zip
  - ren SDL2-devel-%SDL_VERSION%-VC sdl2
  - SET SDL2DIR=sdl2/SDL2-%SDL_VERSION%

  # Installs SDL2 image
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-%IMG_VERSION%-VC.zip
  - unzip -o SDL2_image-devel-%IMG_VERSION%-VC.zip
  - ren SDL2_image-devel-%IMG_VERSION%-VC sdl2_image
  - SET SDL2IMAGEDIR=sdl2_image/SDL2_image-%IMG_VERSION%

  # Installs SDL2 mixer
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-%MIX_VERSION%-VC.zip
  - unzip -o SDL2_mixer-devel-%MIX_VERSION%-VC.zip
  - ren SDL2_mixer-devel-%MIX_VERSION%-VC sdl2_mixer
  - SET SDL2MIXERDIR=sdl2_mixer/SDL2_mixer-%MIX_VERSION%

  # Installs SDL2 ttf
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-%TTF_VERSION%-VC.zip
  - unzip -o SDL2_ttf-devel-%TTF_VERSION%-VC.zip
  - ren SDL2_ttf-devel-%TTF_VERSION%-VC sdl2_ttf
  - SET SDL2TTFDIR=sdl2_ttf/SDL2_ttf-%TTF_VERSION%

before_build:
  - mkdir build
  - cd build 
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -G Ninja

build_script:
  - ninja

test:
  - cd test
  - Centurion_test.exe