dist: trusty
os: linux
language: cpp
compiler: gcc

notifications:
  email: false

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CXX_FLAGS=""
    - ENABLE_COVERAGE=true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - lcov
      - doxygen
      - valgrind

before_install:
  - sudo apt-get update
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libasound2-dev libpulse-dev doxygen
  - sudo apt-get update
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
  # Download and install recent cmake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - sudo apt-get update

  # Manually installs LCOV 1.14
  - wget -c http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
  - tar -xf lcov-1.14.tar.gz
  - cd lcov-1.14
  - sudo make install
  - cd

#  # Manually installs Doxygen 1.8.18
#  - wget -c https://sourceforge.net/projects/doxygen/files/rel-1.8.18/doxygen-1.8.18.linux.bin.tar.gz
#  - tar -xf doxygen-1.8.18.linux.bin.tar.gz
#  - cd doxygen-1.8.18
#  - sudo make install
#  - cd

before_script:
  # Emulates a video device
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8

  - gcc -v
  - g++ -v
  - cmake --version
  - doxygen --version

  # Install core SDL2
  - travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.12.tar.gz | tar xz
  - cd SDL2-2.0.12
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_image
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz | tar xz
  - cd SDL2_image-2.0.5
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_ttf
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz | tar xz
  - cd SDL2_ttf-2.0.15
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_mixer
  - mkdir SDL2_mixer
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz | tar xz
  - cd SDL2_mixer-2.0.4
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - cd ${TRAVIS_BUILD_DIR}

  - doxygen Doxyfile

  - mkdir -p build
  - cd build

  - cmake ${CMAKE_OPTIONS} --DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Debug ..
  - make

  - cd test
  - ctest

  - valgrind --leak-check=full \
             --show-leak-kinds=all \
             --track-origins=yes \
             ./Centurion_test

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info --gcov-tool gcov-8
  - lcov --remove coverage.info '*/test/*' '*/lib/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"