language: cpp

dist: trusty
sudo: require

compiler: gcc

notifications: 
  email: false

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_install:
  - sudo apt-get update -qq

  - mkdir SDL
  - cd SDL

  # Install core SDL2
  - mkdir SDL2_core
  - cd SDL2_core
  - travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.10.tar.gz | tar xz
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_image
  - mkdir SDL2_image¨
  - cd SDL2_image
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz | tar xz
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_ttf
  - mkdir SDL2_ttf
  - cd SDL2_ttf
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz | tar xz
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_mixer
  - mkdir SDL2_mixer
  - cd SDL2_mixer
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz | tar xz
  - ./configure
  - make
  - sudo make install
  - cd ..

install:
  # Download and install recent cmake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

script:
  - export CXX=g++-8
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} ..
  - make Centurion_test
  - ctest

  # - cmake --version
  # - cmake CMakeLists.txt
  # - cmake  --build . --target neat

# matrix:
#   include:
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-8
#       env:
#         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

# install:
#   - wget http://cmake.org/files/v3.16/cmake-3.16.0.tar.gz
#   #- wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz
#   - tar xf cmake-3.16.0.tar.gz
#   - mkdir cmakedir
#   - cd cmakedir
#   #- ./bootstrap --system-curl
#   #- make
#   - sudo make install
#   - cd ..

# before_script:
#   - mkdir build
#   - cd build
#   - cmake ..

# script:
#   - cmake --build .
#   - ctest --verbose