dist: focal

os: linux

language: cpp

compiler: gcc

notifications:
  email: false

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - ENABLE_COVERAGE=true

addons:
  apt:
    packages:
      - doxygen
      - valgrind
      - xvfb
      - mesa-utils
      - linux-generic
      - xserver-xorg-core
      - xserver-xorg
      - xserver-xorg-video-all
      - xserver-xorg-input-all
      - libwayland-egl1-mesa
      - ninja-build

before_install:
  - sudo apt-get update
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libasound2-dev libpulse-dev #doxygen

install:
  - sudo apt-get update
  - sudo apt-get install -y libjson-perl

  # Manually builds latest LCOV
  - git clone https://github.com/linux-test-project/lcov.git lcov
  - cd lcov
  - sudo make install
  - cd ..

before_script:
  # Emulates a video device
  - /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
  - export SDL_VIDEODRIVER=x11;
  - export DISPLAY=:99.0;
  - sleep 3 # give xvfb some time to start

  - g++ --version
  - cmake --version
  - ninja --version
  - doxygen --version
  - lcov --version

  # Install core SDL2
  - travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.14.tar.gz | tar xz
  - cd SDL2-2.0.14
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_image
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz | tar xz
  - cd SDL2_image-2.0.5
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_ttf
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz | tar xz
  - cd SDL2_ttf-2.0.15
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Install SDL2_mixer
  - mkdir SDL2_mixer
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz | tar xz
  - cd SDL2_mixer-2.0.4
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - cd ${TRAVIS_BUILD_DIR}

  - |
    if [[ "${TRAVIS_BRANCH}" == "main" ]]; then
      doxygen
    fi

  - mkdir -p build
  - cd build

  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCEN_AUDIO=OFF -DCEN_COVERAGE=ON -GNinja
  - ninja CenturionTests
  - ninja CenturionMocks

  # Run mocked tests
  - cd test/mocks
  - ./CenturionMocks

  # Run unit tests that use real SDL2 functions
  - cd ..
  - cd unittests
  - ./CenturionTests

  # Only run Valgrind on unit test executable
  - valgrind --leak-check=yes --gen-suppressions=all --suppressions=resources/suppressions.sup ./CenturionTests

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doxygen-out/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info --gcov-tool gcov-9
  - lcov --remove coverage.info '*/test/*' '*/lib/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"