name: "Doxygen"

on:
  push:
    branches:
      - main

env:
  DOXYGEN_VERSION: 1.9.1

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: lukka/get-cmake@v3.18.3

      - name: Update packages
        shell: bash
        run: sudo apt update

      - name: Install packages
        shell: bash
        run: |
          sudo apt install flex
          sudo apt install bison
          sudo apt install tar

      - name: Install Doxygen
        shell: bash
        run: |
          wget https://doxygen.nl/files/doxygen-${{env.DOXYGEN_VERSION}}.linux.bin.tar.gz
          gunzip doxygen-${{env.DOXYGEN_VERSION}}.linux.bin.tar.gz
          tar xf doxygen-${{env.DOXYGEN_VERSION}}.linux.bin.tar
          cd doxygen-${{env.DOXYGEN_VERSION}}
          make install

      - name: Generate Doxygen output
        shell: bash
        run: doxygen

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: doxygen-out/html