name: "Doxygen"

on:
  push:
    branches:
      - main

env:
  DOXYGEN_VERSION: 1.9.1

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: lukka/get-cmake@v3.18.3

      - name: Update packages
        shell: bash
        run: sudo apt update

      - name: Install dependencies required for building Doxygen
        shell: bash
        run: sudo apt install flex bison

      - name: Install Doxygen
        shell: bash
        run: |
          - curl -L https://doxygen.nl/files/doxygen-${{env.DOXYGEN_VERSION}}.src.tar.gz
          - gunzip doxygen-${{env.DOXYGEN_VERSION}}.src.tar.gz
          - tar xf doxygen-${{env.DOXYGEN_VERSION}}.src.tar
          - cd doxygen-${{env.DOXYGEN_VERSION}}
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja
          - ninja
          - sudo make install

      - name: Generate Doxygen output
        shell: bash
        run: doxygen

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: doxygen-out/html