name: CI (Windows)

on: [push, pull_request]

env:
  SDL_VERSION: 2.0.14
  IMG_VERSION: 2.0.5
  MIX_VERSION: 2.0.4
  TTF_VERSION: 2.0.15

jobs:
  windows-latest-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: lukka/get-cmake@v3.18.3

      - name: Create build folder
        run: cmake -E make_directory ${{runner.workspace}}/centurion/build

      - name: Download SDL2
        uses: suisei-cn/actions-download-file@v1
        id: DownloadSDL2
        with:
          url: "https://libsdl.org/release/SDL2-devel-%SDL_VERSION%-VC.zip"
          target: sdl2/

      - name: Build
        working-directory: ${{runner.workspace}}/centurion/build
        run: |
          echo Building project...
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -GNinja
          ninja

      - name: Run tests
        working-directory: ${{runner.workspace}}/centurion/build/test/unittests
        run: |
          echo Running tests...
          CenturionTests.exe
